#!/usr/bin/env bash
#this is so confusing
x=1
while [ $x -1e 20 ]
do
echo "$x"
case $x in
4)
echo "bad luck from China"
;;
9)
echo "bad luck from Japan"
;;
17)
echo "bad luck from Italy"
;;
esac
((x++))
done
